### ISSUE TITLE
Improve handling of new lines

### ISSUE THREAD

**Issue by olance** [xijo/reverse_markdown#39]
Using this HTML:

```
<p><strong>Some text<br><br>other text</strong></p>
```

I end up with:

```
**Some text

other text**
```

New lines inside emphasis tags should be handled specifically to avoid this problem.

**Comment by vaskaloidis** [comment]
I agree with @danschultzer  - we should not be creating extra paragraphs.

And on a second note - while this tool is not technically meant to cover all the use cases for a round trip HTML > Markdown > Html scenario, realistically it is almost always going to be used for this, so I think it'd be good to keep this in mind when deciding issues like this. 

I only say this because Markdown by itself is technically useless.. It's real purpose is to be used as an 'in-between' for HTML; allowing users to style text without having to write ugly HTML. The proof for this is that web-browser's can't parse Markdown, only HTML, so a conversion to Markdown should always be expected to be converted back into HTML. Obviously there are many exceptions to this and many other use cases, but the majority of use-cases fall into this category.
